-- MySQL Script generated by MySQL Workbench
-- 03/21/17 12:21:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema team_project_imdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `cat_title` VARCHAR(32) NULL COMMENT '',
  PRIMARY KEY (`cat_id`)  COMMENT '',
  UNIQUE INDEX `cat_id_UNIQUE` (`cat_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support` (
  `sup_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `sup_name` VARCHAR(32) NULL COMMENT '',
  PRIMARY KEY (`sup_id`)  COMMENT '',
  UNIQUE INDEX `sup_id_UNIQUE` (`sup_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie` (
  `mov_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `mov_title` VARCHAR(255) NULL COMMENT '',
  `mov_year` YEAR NOT NULL COMMENT '',
  `mov_path` VARCHAR(255) NULL COMMENT '',
  `mov_info` TEXT NULL COMMENT '',
  `mov_support` VARCHAR(32) NULL COMMENT '',
  `mov_inserted` TIMESTAMP NOT NULL COMMENT '',
  `mov_actors` TEXT NULL COMMENT '',
  `categories_cat_id` INT UNSIGNED NOT NULL COMMENT '',
  `support_sup_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`mov_id`, `categories_cat_id`, `support_sup_id`)  COMMENT '',
  UNIQUE INDEX `idmovie_UNIQUE` (`mov_id` ASC)  COMMENT '',
  INDEX `fk_movie_categories_idx` (`categories_cat_id` ASC)  COMMENT '',
  INDEX `fk_movie_support1_idx` (`support_sup_id` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
