-- MySQL Script generated by MySQL Workbench
-- 03/20/17 14:25:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema team_project_imdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_title` VARCHAR(32) NULL,
  PRIMARY KEY (`cat_id`),
  UNIQUE INDEX `cat_id_UNIQUE` (`cat_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `support` (
  `sup_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sup_name` VARCHAR(32) NULL,
  PRIMARY KEY (`sup_id`),
  UNIQUE INDEX `sup_id_UNIQUE` (`sup_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie` (
  `mov_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mov_title` VARCHAR(255) NULL,
  `mov_year` YEAR NOT NULL,
  `mov_path` VARCHAR(255) NULL,
  `mov_info` TEXT NULL,
  `mov_support` VARCHAR(32) NULL,
  `mov_inserted` TIMESTAMP NOT NULL,
  `mov_actors` TEXT NULL,
  `categories_cat_id` INT UNSIGNED NOT NULL,
  `support_sup_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`mov_id`, `categories_cat_id`, `support_sup_id`),
  UNIQUE INDEX `idmovie_UNIQUE` (`mov_id` ASC),
  INDEX `fk_movie_categories_idx` (`categories_cat_id` ASC),
  INDEX `fk_movie_support1_idx` (`support_sup_id` ASC),
  CONSTRAINT `fk_movie_categories`
    FOREIGN KEY (`categories_cat_id`)
    REFERENCES `categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_support1`
    FOREIGN KEY (`support_sup_id`)
    REFERENCES `support` (`sup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
